spring:
  application:
    name: OrderService
  config:
    activate:
      on-profile: prod
  cache:
    type: redis
    cache-names: redis-cache
  data:
    redis:
      host: redis
      port: 6379
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
  datasource:
    url: jdbc:postgresql://localhost:5434/stroy1click
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  flyway:
    url: jdbc:postgresql://localhost:5434/stroy1click
    user: postgres
    password: password
    baseline-on-migrate: true
  messages:
    basename: messages
    encoding: UTF-8
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        acks: all
        enable.idempotence: true
        delivery.timeout.ms: 120000
        linger.ms: 0
        request.timeout.ms: 30000
        max.in.flight.requests.per.connection: 4

redisson:
  host: 127.0.0.1
  port: 6379
  username: default
  password: password

resilience4j:
  ratelimiter:
    instances:
      orderLimiter:
        limitForPeriod: 100
        limitRefreshPeriod: 1s

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

otel:
  service:
    name: "confirmation-code-service"
  traces:
    exporter: "otlp"
    sampler: "always_on"
  metrics:
    exporter: "otlp"
    export:
      interval: 5000
  logs:
    exporter: "otlp"
  exporter:
    otlp:
      protocol: "grpc"
      endpoint: "http://localhost:4317"
server:
  port: 1010
