create schema if not exists ordering;

create table if not exists ordering.orders(
                                              id bigint primary key generated by default as identity ,
                                              legal_name varchar not null ,
                                              legal_form varchar not null ,
                                              notes varchar(10000) not null ,
                                              delivery_address varchar not null ,
                                              inn varchar not null ,
                                              kpp varchar not null ,
                                              order_status varchar not null ,
                                              created_at timestamp not null ,
                                              updated_at timestamp not null ,
                                              contact_name varchar not null ,
                                              contact_phone varchar(12) not null ,
                                              contact_email varchar not null ,
                                              user_id bigint not null
);

create table if not exists ordering.order_items(
                                                   id bigint primary key generated by default as identity ,
                                                   quantity int not null ,
                                                   product_id int not null ,
                                                   product_title varchar not null ,
                                                   price decimal(19, 2) not null,
                                                   unit varchar not null ,
                                                   order_id bigint references ordering.orders(id)
);

create schema if not exists outbox;

create table if not exists outbox.outbox_events(
                                                   id bigint generated by default as identity primary key ,
                                                   topic varchar not null ,
                                                   class_type varchar not null ,
                                                   payload varchar not null ,
                                                   created_at timestamp not null ,
                                                   updated_at timestamp not null ,
                                                   send_at timestamp ,
                                                   status varchar not null ,
                                                   error_message varchar ,
                                                   retry_attempts int not null
);

-- Test: OrderTests get()
-- Описание: Заказ для проверки метода получения заказа
insert into ordering.orders (id, notes, order_status, created_at, updated_at, contact_phone, user_id, legal_name,
                             legal_form,contact_name, contact_email, inn, kpp, delivery_address)
values (
           1,
           'Тестовый заказ для проверки получения.',
           'CREATED',
           '2024-10-01 10:00:00',
           '2024-10-01 10:00:00',
           '+79101234567',
           501,
        'Company Name',
        'LLC',
        'Contact Name',
        '80000000000',
        '1234567890',
        '123456789',
        'San-Francisco'
       );

-- Test: OrderTests update()
-- Описание: Заказ для проверки метода обновления заказа
insert into ordering.orders (id, notes, order_status, created_at, updated_at, contact_phone, user_id, legal_name,
                             legal_form,contact_name, contact_email, inn, kpp, delivery_address)
values (
           2,
           'Тестовый заказ для проверки обновления.',
           'CREATED',
           '2024-09-15 12:00:00',
           '2024-09-15 12:00:00',
           '+79039876543',
           502,
           'Company Name',
           'LLC',
           'Contact Name',
           '80000000000',
           '1234567890',
           '123456789',
           'San-Francisco'
       );

-- Test: OrderTests delete()
-- Описание: Заказ для проверки метода удаления заказа
insert into ordering.orders (id, notes, order_status, created_at, updated_at, contact_phone, user_id, legal_name,
                             legal_form,contact_name, contact_email, inn, kpp, delivery_address) values (
           3,
           'Тестовый заказ для проверки удаления.',
           'CREATED',
           '2024-08-10 09:30:00',
           '2024-08-10 09:30:00',
           '+79876543210',
           503,
           'Company Name',
           'LLC',
           'Contact Name',
           '80000000000',
           '1234567890',
           '123456789',
           'San-Francisco'
       );

-- Test: OrderItemTests get()
-- Описание: Позиции заказа для проверки получения заказа
insert into ordering.order_items (id, quantity, product_id, order_id, product_title, price, unit)
values (1, 2, 10, 1, 'Product Title', 123.00, 'KG');
insert into ordering.order_items (id, quantity, product_id, order_id, product_title, price, unit)
values (2, 1, 25, 1, 'Product Title', 123.00, 'KG');

SELECT setval('ordering.orders_id_seq', (SELECT MAX(id) FROM ordering.orders));

-- Test: OrderItemTests update()
-- Описание: Позиция заказа для проверки обновления заказа
insert into ordering.order_items (id, quantity, product_id, order_id, product_title, price, unit)
values (3, 3, 12, 2,'Product Title', 123.00, 'KG');

-- Test: OrderItemTests delete()
-- Описание: Позиция заказа для проверки удаления заказа
insert into ordering.order_items (id, quantity, product_id, order_id, product_title, price, unit)
values (4, 4, 7, 3,'Product Title', 123.00, 'KG');

SELECT setval('ordering.order_items_id_seq', (SELECT MAX(id) FROM ordering.order_items));