create schema if not exists ordering;

create table if not exists ordering.orders
(
    id bigint primary key generated by default as identity,
    notes varchar(10000) not null,
    order_status varchar not null,
    created_at timestamp not null,
    updated_at timestamp not null,
    contact_phone varchar(12) not null,
    user_id bigint not null
);

create table if not exists ordering.order_items
(
    id bigint primary key generated by default as identity,
    quantity int not null,
    product_id int not null,
    order_id bigint references ordering.orders (id)
);

-- Test: OrderTests get()
-- Описание: Заказ для проверки метода получения заказа
insert into ordering.orders (id, notes, order_status, created_at, updated_at, contact_phone, user_id)
values (
           1,
           'Тестовый заказ для проверки получения.',
           'CREATED',
           '2024-10-01 10:00:00',
           '2024-10-01 10:00:00',
           '+79101234567',
           501
       );

-- Test: OrderTests update()
-- Описание: Заказ для проверки метода обновления заказа
insert into ordering.orders (id, notes, order_status, created_at, updated_at, contact_phone, user_id)
values (
           2,
           'Тестовый заказ для проверки обновления.',
           'CREATED',
           '2024-09-15 12:00:00',
           '2024-09-15 12:00:00',
           '+79039876543',
           502
       );

-- Test: OrderTests delete()
-- Описание: Заказ для проверки метода удаления заказа
insert into ordering.orders (id, notes, order_status, created_at, updated_at, contact_phone, user_id)
values (
           3,
           'Тестовый заказ для проверки удаления.',
           'CREATED',
           '2024-08-10 09:30:00',
           '2024-08-10 09:30:00',
           '+79876543210',
           503
       );

-- Test: OrderItemTests get()
-- Описание: Позиции заказа для проверки получения заказа
insert into ordering.order_items (id, quantity, product_id, order_id)
values (1, 2, 10, 1);
insert into ordering.order_items (id, quantity, product_id, order_id)
values (2, 1, 25, 1);

SELECT setval('ordering.orders_id_seq', (SELECT MAX(id) FROM ordering.orders));

-- Test: OrderItemTests update()
-- Описание: Позиция заказа для проверки обновления заказа
insert into ordering.order_items (id, quantity, product_id, order_id)
values (3, 3, 12, 2);

-- Test: OrderItemTests delete()
-- Описание: Позиция заказа для проверки удаления заказа
insert into ordering.order_items (id, quantity, product_id, order_id)
values (4, 4, 7, 3);

SELECT setval('ordering.order_items_id_seq', (SELECT MAX(id) FROM ordering.order_items));