create schema if not exists ordering;

create table if not exists ordering.orders(
    id bigint primary key generated by default as identity ,
    legal_name varchar not null ,
    legal_form varchar not null ,
    notes varchar(10000) not null ,
    delivery_address varchar not null ,
    inn varchar not null ,
    kpp varchar ,
    order_status varchar not null ,
    created_at timestamp not null ,
    updated_at timestamp not null ,
    contact_name varchar not null ,
    contact_phone varchar(12) not null ,
    contact_email varchar not null ,
    user_id bigint not null
);

create table if not exists ordering.order_items(
    id bigint primary key generated by default as identity ,
    quantity int not null ,
    product_id int not null ,
    product_title varchar not null ,
    price decimal(19, 2) not null,
    unit varchar not null ,
    order_id bigint references ordering.orders(id)
);