create schema if not exists ordering;

create table if not exists ordering.orders(
    id bigint primary key generated by default as identity ,
    notes varchar(10000) not null ,
    order_status varchar not null ,
    created_at timestamp not null ,
    updated_at timestamp not null ,
    contact_phone varchar(12) not null ,
    user_id bigint not null
);

create table if not exists ordering.order_items(
    id bigint primary key generated by default as identity ,
    quantity int not null ,
    product_id int not null ,
    order_id bigint references ordering.orders(id)
);