create schema if not exists outbox;

create table if not exists outbox.outbox_events(
    id bigint generated by default as identity primary key ,
    topic varchar not null ,
    class_type varchar not null ,
    payload varchar not null ,
    created_at timestamp not null ,
    updated_at timestamp not null ,
    send_at timestamp ,
    status varchar not null ,
    error_message varchar ,
    retry_attempts int not null
)